### ISSUE TITLE
Make a RegistrationWorkflows class that contains methods calling an abstract RegistrantRepo interface, which has a ZoomRegistrantRepo implementation. Have automated tests in place for each workflow method and each ZoomRegistrantRepo method, that doesn't call the Zoom API (i.e. goal is to have fast tests)

### ISSUE THREAD

**Issue by mohammadbashiri** [ibehave-ibots/iBOTS-Tools#15] opened 2023-07-24 17:03 UTC
- [ ] RegistrationWorkflows class
- [ ] InMemoryRegistrantRepo class, for integration testing of RegistrantWorkflows with AttendeeRepo interface
- [ ] ZoomRegistrantRepo class, for adapting Zoom REST API to the project.
- [ ] Unit Tests of ZoomRegistrantRepo methods, patching out request.get calls with simulated Zoom responses, for quick testing.

**Comment by nickdelgrosso** [comment] 2023-07-25 08:07
Related to #16 (accidental duplicate of this issue)

**Closed** 2023-07-28 09:27 UTC
